set_temperature:
  name: Set Temperature
  description: Set the target temperature of the hot tub.
  fields:
    temperature:
      name: Temperature
      description: Target temperature in Celsius
      required: true
      selector:
        number:
          min: 20
          max: 40
          step: 1
          unit_of_measurement: °C

set_heater:
  name: Set Heater
  description: Turn the heater on or off
  fields:
    state:
      name: State
      description: on or off
      required: true
      selector:
        select:
          options:
            - "on"
            - "off"

set_bubble:
  name: Set Bubble
  description: Turn the bubble feature on or off.
  fields:
    state:
      name: State
      description: on or off
      required: true
      selector:
        select:
          options:
            - "on"
            - "off"

set_bubble_level:
  name: Set Bubble Level
  description: Set the bubble level of the hot tub.
  fields:
    level:
      name: Level
      description: Bubble level (1-3)
      required: true
      selector:
        number:
          min: 1
          max: 3
          step: 1

set_jet:
  name: Set Jet
  description: Turn the jet feature on or off.
  fields:
    state:
      name: State
      description: on or off
      required: true
      selector:
        select:
          options:
            - "on"
            - "off"

set_filter:
  name: Set Filter
  description: Turn the filter feature on or off.
  fields:
    state:
      name: State
      description: on or off
      required: true
      selector:
        select:
          options:
            - "on"
            - "off"
