name: Zip me up

on:
    push:
        tags:
            - "v*.*.*"

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Zip artifact
        uses: vimtor/action-zip@v1.2
        id: create_zip
        with:
          files: custom_components/ 
          dest: mspa.zip
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mspa-download
          path: ${{ github.workspace }}/mspa.zip
      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: ${{ github.workspace }}/mspa.zip
