name: Zip me up

on:
    push:
        tags:
            - "v*.*.*"

permissions:
  contents: read

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: vimtor/action-zip@v1.2
        id: create_zip
        with:
          files: custom_components/ 
          dest: mspa.zip
      - uses: actions/upload-artifact@v4
        with:
          name: mspa download
          path: ${{ github.workspace }}/mspa.zip
