name: Zip me up

on:
    push:
        tags:
            - "v*.*.*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: echo "(zipped artifact)" > ${{ github.workspace }}/custom_components/mspa/README.md
        
      # Pack the MSPA dir as a zip and upload to the release
      - name: 📦 ZIP MSPA Dir
        if: ${{ github.event_name == 'release' }}
        run: |
          cd ${{ github.workspace }}/custom_components/mspa
          zip mspa.zip -r ./

      - name: Release
        uses: softprops/action-gh-release@v2
        if: ${{ github.event_name == 'release' }}
        with:
          files: ${{ github.workspace }}/custom_components/mspa/mspa.zip
