name: Zip me up

on:
    push:
        tags:
            - "v*.*.*"

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Zip artifact
        uses: vimtor/action-zip@v1.2
        id: create_zip
        with:
          files: custom_components/ 
          dest: mspa.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
            draft: true
            generate_release_notes: true
            files: ${{ github.workspace }}/mspa.zip
